
Vagrant.configure(2) do |config|
  config.vm.define "controller" do |controller|
    controller.vm.box = "hashicorp/bionic64"
    controller.vm.box_check_update = true
    controller.vm.network "private_network", ip: "192.168.56.5"
    controller.vm.hostname = "ansible"
    controller.vm.provision "shell", path: "../scripts/ansible.sh"
  controller.vm.synced_folder "../../../Ansible-Registry", "/home/vagrant/ansible", disabled = false
  
    controller.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 512
        vb.name = "Ansible Controller Node"
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
        vb.customize ["modifyvm", :id, "--audio", "none"]
        vb.customize ["modifyvm", :id, "--iconfile", "../images/Ansible_Logo.png"]
        vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
        vb.customize ["modifyvm", :id, "--vram", "2"]
    end
  end
end